### ISSUE TITLE
Converted results are displayed with precision error

### ISSUE THREAD

**Issue by biozid-0208** [tanvir002700/convert_unit#6]
The converted numbers are displayed with the precision error.
  **For example:**

> ConvertUnit::Length.new(9, 'm').to('km')
> prints: 0.009000000000000001km

**Comment by tanvir002700** [comment]
I've solve this issue with BigDecimal ruby class. 
Here is the [pull](https://github.com/tanvir002700/convert_unit/pull/10) req . It'll be available to next release.
